In [1]:
import tensorflow as tf

In [2]:
# 创建变量
# tf.random_normal 方法返回形状为(1，4)的张量。它的4个元素符合均值为100、标准差为0.35的正态分布。
W = tf.Variable(initial_value=tf.random_normal(shape=(1, 4), mean=100, stddev=0.35), name="W")
b = tf.Variable(tf.zeros([4]), name="b")

In [3]:
[W, b]

[<tf.Variable 'W:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b:0' shape=(4,) dtype=float32_ref>]

In [6]:
# 初始化变量
# 创建会话（之后小节介绍）
sess = tf.Session()
# 使用 global_variables_initializer 方法初始化全局变量 W 和 b
sess.run(tf.global_variables_initializer())
# 执行操作，获取变量值
sess.run([W, b])

[array([[100.160286,  99.81771 , 100.11922 ,  99.9707  ]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [9]:
# 执行更新变量 b 的操作
sess.run(tf.assign_add(b, [3, 4, 5, 6]))

array([4., 5., 6., 7.], dtype=float32)

In [10]:
# 查看变量 b 是否更新成功
sess.run(b)

array([4., 5., 6., 7.], dtype=float32)

### Saver 使用示例
```PYTHON
v1 = tf.Variable(..., name='v1')
v2 = tf.Variable(..., name='v2')
# 指定需要保存和恢复的变量
saver = tf.train.Saver({'v1': v1, 'v2': v2})
saver = tf.train.Saver([v1, v2])
saver = tf.train.Saver({v.op.name: v for v in [v1, v2]})
# 保存变量的方法
tf.train.saver.save(sess, 'my-model', global_step=0) # ==> filename: 'my-model-0'
```

In [11]:
# 创建Saver
saver = tf.train.Saver({'W': W, 'b': b})
# 存储变量到文件 './summary/test.ckpt-0'
saver.save(sess, './summary/test1.ckpt', global_step=0)

'./summary/test1.ckpt-0'

In [12]:
# 再次执行更新变量 b 的操作
sess.run(tf.assign_add(b, [1, 1, 1, 1]))
# 获取变量 b 的最新值
sess.run(b)

array([5., 6., 7., 8.], dtype=float32)

In [13]:
# 从文件中恢复变量 b 的值
saver.restore(sess, './summary/test.ckpt-0')
# 查看变量 b 是否恢复成功
sess.run(b)

INFO:tensorflow:Restoring parameters from ./summary/test.ckpt-0


array([1., 1., 1., 1.], dtype=float32)

In [ ]:
# 从文件中恢复数据流图结构
# tf.train.import_meta_graph